### ISSUE TITLE
Depreciated warning on PHP 8

### ISSUE THREAD

**Issue by curious-toad** [wpcodefactory/product-quantity-for-woocommerce#1]
Thanks for this very handy plugin! Been using it for a while on a site which runs on PHP 7.4. My hosting provider is upgrading to PHP 8.2, which is more strict about dynamic classes.

When loading a category or product page, I’m getting the following php warning:

Deprecated: Creation of dynamic property Alg_WC_PQ_Core::$is_wc_version_below_3 is deprecated in /nas/content/live/devukbambooltd/wp-content/plugins/product-quantity-for-woocommerce/includes/class-alg-wc-pq-core.php on line 2643

This is appearing despite disabling wp_debug. Do you have a fix for this to endure it’s fully compatible with PHP 8.2?

**Comment by kousikmukherjee** [comment]
The issue has been fixed and now it's closed.

**Comment by curious-toad** [comment]
Great, thanks so much for the update here. Just tested again and all working well.
